export const dataUsers = [
  {
    athlete_id: 123456,
    name: "Eric",
    activities: [
      {
        id: 1,
        name: "Carrera matutina",
        type: "Run",
        date: "2023-12-01",
        distance: 10.5,
        time: "00:50:00",
        elevation_gain: 100,
      },
      {
        id: 2,
        name: "Paseo en bicicleta",
        type: "Ride",
        date: "2023-12-05",
        distance: 25.3,
        time: "01:30:00",
        elevation_gain: 200,
      },
      {
        id: 3,
        name: "Natación en la piscina",
        type: "Swim",
        date: "2023-12-10",
        distance: 1.5,
        time: "00:25:00",
        elevation_gain: 0,
      },
      {
        id: 4,
        name: "Entrenamiento en el gimnasio",
        type: "Workout",
        date: "2023-12-15",
        distance: 0,
        time: "00:45:00",
        elevation_gain: 0,
      },
      {
        id: 5,
        name: "Caminata nocturna",
        type: "Walk",
        date: "2023-12-20",
        distance: 8.0,
        time: "01:15:00",
        elevation_gain: 50,
      },
    ],
  },
  {
    athlete_id: 123456,
    name: "Hiromi",
    activities: [
      {
        id: 1,
        name: "Carrera matutina",
        type: "Run",
        date: "2023-12-01",
        distance: 10.5,
        time: "00:50:00",
        elevation_gain: 100,
      },
      {
        id: 2,
        name: "Paseo en bicicleta",
        type: "Ride",
        date: "2023-12-05",
        distance: 25.3,
        time: "01:30:00",
        elevation_gain: 200,
      },
      {
        id: 3,
        name: "Natación en la piscina",
        type: "Swim",
        date: "2023-12-10",
        distance: 1.5,
        time: "00:25:00",
        elevation_gain: 0,
      },
      {
        id: 4,
        name: "Entrenamiento en el gimnasio",
        type: "Workout",
        date: "2023-12-15",
        distance: 0,
        time: "00:45:00",
        elevation_gain: 0,
      },
      {
        id: 5,
        name: "Caminata nocturna",
        type: "Walk",
        date: "2023-12-20",
        distance: 8.0,
        time: "01:15:00",
        elevation_gain: 50,
      },
    ],
  },

  
];
