export const dataUsers = [
  {
    athlete_id: 123456,
    name: "Usuario 1",
    activities: [
      {
        id: 1,
        name: "Carrera matutina",
        type: "Run",
        date: "2023-12-10",
        distance: 10.5,
        time: "00:50:00",
        elevation_gain: 100,
      },
      {
        id: 2,
        name: "Paseo en bicicleta",
        type: "Ride",
        date: "2023-12-05",
        distance: 25.3,
        time: "01:30:00",
        elevation_gain: 200,
      },
      {
        id: 3,
        name: "Natación en la piscina",
        type: "Swim",
        date: "2023-11-30",
        distance: 1.5,
        time: "00:25:00",
        elevation_gain: 0,
      },
      {
        id: 4,
        name: "Entrenamiento en el gimnasio",
        type: "Workout",
        date: "2023-11-22",
        distance: 0,
        time: "00:45:00",
        elevation_gain: 0,
      },
      {
        id: 1,
        name: "Carrera matutina",
        type: "Run",
        date: "2023-11-18",
        distance: 8.0,
        time: "01:15:00",
        elevation_gain: 50,
      },
      {
        id: 5,
        name: "Paseo en bicicleta",
        type: "Run",
        date: "2023-11-10",
        distance: 8.0,
        time: "01:15:00",
        elevation_gain: 50,
      },
      {
        id: 5,
        name: "Paseo en bicicleta",
        type: "Walk",
        date: "2023-11-02",
        distance: 8.0,
        time: "01:15:00",
        elevation_gain: 50,
      },
      {
        id: 5,
        name: "Entrenamiento en el gimnasio",
        type: "Walk",
        date: "2023-10-20",
        distance: 8.0,
        time: "01:15:00",
        elevation_gain: 50,
      },
      {
        id: 5,
        name: "Caminata nocturna",
        type: "Walk",
        date: "2023-10-18",
        distance: 8.0,
        time: "01:15:00",
        elevation_gain: 50,
      },
      {
        id: 5,
        name: "Entrenamiento en el gimnasio",
        type: "Walk",
        date: "2023-10-12",
        distance: 8.0,
        time: "01:15:00",
        elevation_gain: 50,
      },
      {
        id: 5,
        name: "Natación en la piscina",
        type: "Walk",
        date: "2023-10-10",
        distance: 8.0,
        time: "01:15:00",
        elevation_gain: 50,
      },
      {
        id: 5,
        name: "Caminata nocturna",
        type: "Walk",
        date: "2023-10-03",
        distance: 8.0,
        time: "01:15:00",
        elevation_gain: 50,
      },
    ],
  },
  {
    athlete_id: 234567,
    name: "Usuario 2",
    activities: [
      {
        id: 1,
        name: "Paseo en bicicleta",
        type: "Run",
        date: "2023-12-08",
        distance: 10.5,
        time: "00:40:00",
        elevation_gain: 100,
      },
      {
        id: 2,
        name: "Carrera nocturna",
        type: "Ride",
        date: "2023-12-05",
        distance: 8.3,
        time: "01:20:00",
        elevation_gain: 200,
      },
      {
        id: 3,
        name: "Natación en la piscina",
        type: "Swim",
        date: "2023-11-28",
        distance: 1.5,
        time: "00:35:00",
        elevation_gain: 0,
      },
      {
        id: 4,
        name: "Entrenamiento en el gimnasio",
        type: "Workout",
        date: "2023-11-23",
        distance: 0,
        time: "01:45:00",
        elevation_gain: 0,
      },
      {
        id: 5,
        name: "Caminata nocturna",
        type: "Run",
        date: "2023-11-15",
        distance: 5.0,
        time: "00:20:00",
        elevation_gain: 50,
      },
      {
        id: 5,
        name: "Caminata nocturna",
        type: "Run",
        date: "2023-11-10",
        distance: 3.0,
        time: "00:30:00",
        elevation_gain: 50,
      },
      {
        id: 5,
        name: "Caminata nocturna",
        type: "Walk",
        date: "2023-11-03",
        distance: 2.0,
        time: "00:25:00",
        elevation_gain: 50,
      },
      {
        id: 5,
        name: "Caminata nocturna",
        type: "Walk",
        date: "2023-10-25",
        distance: 3.0,
        time: "01:35:00",
        elevation_gain: 50,
      },
      {
        id: 5,
        name: "Caminata nocturna",
        type: "Walk",
        date: "2023-10-19",
        distance: 10.0,
        time: "01:55:00",
        elevation_gain: 50,
      },
      {
        id: 5,
        name: "Caminata nocturna",
        type: "Walk",
        date: "2023-10-13",
        distance: 5.0,
        time: "01:25:00",
        elevation_gain: 50,
      },
      {
        id: 5,
        name: "Caminata nocturna",
        type: "Walk",
        date: "2023-10-19",
        distance: 8.0,
        time: "01:35:00",
        elevation_gain: 50,
      },
      {
        id: 5,
        name: "Caminata nocturna",
        type: "Walk",
        date: "2023-10-03",
        distance: 7.0,
        time: "01:45:00",
        elevation_gain: 50,
      },
    ],
  },
  
];
